-- Implement a banking environment with following tables, procedures and function.
-- bank_customer(cust_id,cust_name,email)
-- cust_id is the primary key and it must be auto generated by the databse system.
-- account(acc_no,acc_type,cust_id,balance)
-- acc_no is the primary key and cust_id is foreign key.
-- The account_type field will accept ONLY two values saving and current. 
-- if the account type is saving then the minimum balance should be RS.1000 however there is no minimum balance condition for the current account.

-- 1. Import DATA of account table from a csv file. [Download CSV]
-- mysql> SHOW GLOBAL VARIABLES LIKE 'local_infile';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| local_infile  | OFF   |
+---------------+-------+
1 row in set (0.90 sec)

mysql> SET GLOBAL local_infile=1;
Query OK, 0 rows affected (0.05 sec)

mysql> SHOW GLOBAL VARIABLES LIKE 'local_infile';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| local_infile  | ON    |
+---------------+-------+
1 row in set (0.01 sec)

mysql> quit

mysql> mysql --local-infile=1 -u root -p

mysql> use DBNAME;

mysql> LOAD DATA LOCAL INFILE '/file_name.csv' INTO TABLE table_name FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

-- 2. create a function getBalance(acc_no) to get the balance details of a bank account.
-- 3. create two procedures

    credit(acc_no,amount)

    debit(acc_no,amount)

Display appropriate messages of every operations and errors.
4. Use curosr and create a procedure to list all email ids of customer separated by semicolon;

(Refer: https://www.mysqltutorial.org/mysql-cursor/)

account				

acc_no	acc_type  cust_id	balance

1001	saving		1		10000

1002	saving		2		20000

1003	saving		3		30000

2001	current		4		10000

2002	current		5		20000

bank_customer

cust_id	cust_name 	email

1		hari		hari@gmail.com

2		sam		sam@gmail.com

3		sree		sree@lbscek.ac.in

4		ali		ali@lbscek.ac.in

5		john		john@yahoo.co.in

				

select * from account;				

select getBalance(1001) as currentBalance;				

				

call credit(1001,2000);	12000			

call credit(1004,1000);	ERROR			

call debit(1001,1000);	11000			

call debit(1004,1000);	ERROR			

call debit(1001,10500);	ERROR			

call debit(1001,10000);	1000			

call debit(2001,10000);	0			

select getBalance(2001) as currentBalance;				
select * from account;				




-- 1. Create the bank_customer table
CREATE TABLE bank_customer (
    cust_id INT AUTO_INCREMENT PRIMARY KEY,
    cust_name VARCHAR(50),
    email VARCHAR(100)
);

-- 2. Create the account table
CREATE TABLE account (
    acc_no INT PRIMARY KEY,
    acc_type ENUM('saving', 'current'),
    cust_id INT,
    balance DECIMAL(10, 2),
    FOREIGN KEY (cust_id) REFERENCES bank_customer(cust_id)
);

-- 3. Load data from a CSV file into the account table (use after setting local_infile to ON)
-- You need to prepare the CSV file with the appropriate data and place it in a directory accessible by the MySQL server.

-- Run the following command to load the data into the account table:
-- LOAD DATA LOCAL INFILE '/path_to_file/account.csv' INTO TABLE account
-- FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;

-- 4. Create a function to get the balance of a bank account
DELIMITER //
CREATE FUNCTION getBalance(acc_no INT) 
RETURNS DECIMAL(10, 2)
DETERMINISTIC
BEGIN
    DECLARE balance DECIMAL(10, 2);
    
    SELECT a.balance INTO balance
    FROM account a
    WHERE a.acc_no = acc_no;

    IF balance IS NULL THEN
        SELECT 'Account does not exist' AS message;
    END IF;

    RETURN balance;
END//
DELIMITER ;

-- 5. Create the credit procedure
DELIMITER //
CREATE PROCEDURE credit(IN acc_no INT, IN amount DECIMAL(10, 2))
BEGIN
    DECLARE current_balance DECIMAL(10, 2);

    -- Fetch the balance of the account
    SELECT balance INTO current_balance
    FROM account
    WHERE acc_no = acc_no;

    -- Check if the account exists
    IF current_balance IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Account does not exist';
    ELSE
        -- Update the balance by adding the amount
        UPDATE account
        SET balance = balance + amount
        WHERE acc_no = acc_no;

        SELECT CONCAT('Successfully credited Rs.', amount, ' to account ', acc_no, '. New balance: Rs.', current_balance + amount) AS message;
    END IF;
END//
DELIMITER ;

-- 6. Create the debit procedure
DELIMITER //
CREATE PROCEDURE debit(IN acc_no INT, IN amount DECIMAL(10, 2))
BEGIN
    DECLARE current_balance DECIMAL(10, 2);
    DECLARE account_type ENUM('saving', 'current');

    -- Fetch the balance and account type
    SELECT balance, acc_type INTO current_balance, account_type
    FROM account
    WHERE acc_no = acc_no;

    -- Check if the account exists
    IF current_balance IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Account does not exist';
    ELSE
        -- Check if the withdrawal exceeds the current balance
        IF current_balance < amount THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Insufficient balance';
        ELSEIF account_type = 'saving' AND (current_balance - amount) < 1000 THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cannot go below minimum balance of Rs.1000 for savings account';
        ELSE
            -- Update the balance by subtracting the amount
            UPDATE account
            SET balance = balance - amount
            WHERE acc_no = acc_no;

            SELECT CONCAT('Successfully debited Rs.', amount, ' from account ', acc_no, '. New balance: Rs.', current_balance - amount) AS message;
        END IF;
    END IF;
END//
DELIMITER ;

-- 7. Create a procedure to list all email IDs of customers separated by semicolons using a cursor
DELIMITER //
CREATE PROCEDURE list_customer_emails()
BEGIN
    DECLARE finished INT DEFAULT 0;
    DECLARE email_list TEXT DEFAULT '';
    DECLARE current_email VARCHAR(100);
    
    -- Declare the cursor
    DECLARE customer_cursor CURSOR FOR
    SELECT email FROM bank_customer;
    
    -- Declare a continue handler to end the loop
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET finished = 1;

    -- Open the cursor
    OPEN customer_cursor;

    -- Loop through each email
    email_loop: LOOP
        FETCH customer_cursor INTO current_email;
        IF finished = 1 THEN
            LEAVE email_loop;
        END IF;

        -- Append the current email to the list with a semicolon
        SET email_list = CONCAT(email_list, current_email, ';');
    END LOOP;

    -- Close the cursor
    CLOSE customer_cursor;

    -- Return the final list of emails
    SELECT email_list AS customer_emails;
END//
DELIMITER ;

-- 8. Insert sample data into the bank_customer table
INSERT INTO bank_customer (cust_name, email) VALUES 
('hari', 'hari@gmail.com'),
('sam', 'sam@gmail.com'),
('sree', 'sree@lbscek.ac.in'),
('ali', 'ali@lbscek.ac.in'),
('john', 'john@yahoo.co.in');

-- 9. Insert sample data into the account table
INSERT INTO account (acc_no, acc_type, cust_id, balance) VALUES
(1001, 'saving', 1, 10000),
(1002, 'saving', 2, 20000),
(1003, 'saving', 3, 30000),
(2001, 'current', 4, 10000),
(2002, 'current', 5, 20000);

-- 10. Queries to test the function, procedures, and data
SELECT * FROM account;

-- Get the balance of an account
SELECT getBalance(1001) AS currentBalance;

-- Call the credit procedure
CALL credit(1001, 2000);
CALL credit(1004, 1000); -- This will result in an error

-- Call the debit procedure
CALL debit(1001, 1000);
CALL debit(1004, 1000); -- This will result in an error
CALL debit(1001, 10500); -- This will result in an error (minimum balance violation)
CALL debit(1001, 10000);
CALL debit(2001, 10000);

-- Get the balance of account 2001 after debiting
SELECT getBalance(2001) AS currentBalance;

-- List all email addresses separated by semicolons
CALL list_customer_emails();
